services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD:-postgres}
      POSTGRES_DB: ${PGDB:-db}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-db} -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    ports:
      - 5432:5432

volumes:
  postgres_data:
