services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      NODE_ENV: production
      ENV: 'development'
      POSTGRES_HOST: ${PGHOST:-postgres}
      POSTGRES_PORT: ${PGPORT:-5432}
      POSTGRES_DB: ${PGDB:-db}
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD:-postgres}
      DATABASE_URL: "postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-db}"
      JWT_SECRET: ${JWT_SECRET:-thisisasecret}
      PORT: "8080"
      ACCESS_TOKEN_TTL_MIN: "${ACCESS_TOKEN_TTL_MIN:-60}"
      REFRESH_TOKEN_TTL_DAY: "${REFRESH_TOKEN_TTL_DAY:-3}"
      MAX_CONCURRENCY: "${MAX_CONCURRENCY:-8}"
    depends_on:
      postgres:
       condition : service_healthy
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - ext

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD:-postgres}
      POSTGRES_DB: ${PGDB:-db}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-db} -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    ports:
      - 5432:5432
    networks:
      - ext

  frontend:
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile
    container_name: frontend
    ports:
      - 3000:3000
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    
    env_file:
      - ./frontend/.env.local

    restart: always
    networks:
      - ext
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
  

networks:
  ext:
    driver: bridge

volumes:
  postgres_data:
