// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    name, description, type, script_path, args, env_vars, config, timeout_secs, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, name, description, type, script_path, args, env_vars, config, timeout_secs, created_by, created_at, updated_at
`

type CreateJobParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Type        string      `json:"type"`
	ScriptPath  string      `json:"script_path"`
	Args        []string    `json:"args"`
	EnvVars     []byte      `json:"env_vars"`
	Config      []byte      `json:"config"`
	TimeoutSecs pgtype.Int4 `json:"timeout_secs"`
	CreatedBy   uuid.UUID   `json:"created_by"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.ScriptPath,
		arg.Args,
		arg.EnvVars,
		arg.Config,
		arg.TimeoutSecs,
		arg.CreatedBy,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.ScriptPath,
		&i.Args,
		&i.EnvVars,
		&i.Config,
		&i.TimeoutSecs,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, name, description, type, script_path, args, env_vars, config, timeout_secs, created_by, created_at, updated_at FROM jobs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetJobByID(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.ScriptPath,
		&i.Args,
		&i.EnvVars,
		&i.Config,
		&i.TimeoutSecs,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, name, description, type, script_path, args, env_vars, config, timeout_secs, created_by, created_at, updated_at FROM jobs
WHERE ($3::text IS NULL OR type = $3 )
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListJobsParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Type   pgtype.Text `json:"type"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Limit, arg.Offset, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.ScriptPath,
			&i.Args,
			&i.EnvVars,
			&i.Config,
			&i.TimeoutSecs,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
set
 name = coalesce($2, name),
 description = coalesce($3, description)
WHERE id = $1
RETURNING id, name, description, type, script_path, args, env_vars, config, timeout_secs, created_by, created_at, updated_at
`

type UpdateJobParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob, arg.ID, arg.Name, arg.Description)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.ScriptPath,
		&i.Args,
		&i.EnvVars,
		&i.Config,
		&i.TimeoutSecs,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
